# basic options
title: Aidan John Nunn
author: GitHub User
email: aidanjnunn@outlook.com
description:  Professional profile for my company. Feel free to call me any time on +27 83 302 9930.
twitter_username:  "@AidanJohnNunn1"
github_username:   aidanjnunn

# Build settings
markdown: kramdown
theme: minima
